version: '3'

services:
  app:
    container_name: estoque_e_commerce_flask_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - postgres
  postgres:
    container_name: estoque_e_commerce_flask_db
    image: postgres:13-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "user_test"
      POSTGRES_DB: "estoque_flask"
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data: