version: '3'

services:
  app:
    container_name: estoque_e_commerce_flask_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ${API_PORT}:${API_PORT}
      - "5000:5000"
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
    environment:
      FLASK_DEBUG: "true"
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@{DB_HOST}:${DB_PORT_DOCKER}/${DB_NAME}"

  postgres:
    container_name: estoque_e_commerce_flask_db
    image: postgres:13-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
        - ${DB_PORT}:${DB_PORT_DOCKER}
    volumes:
      - app_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  app_db_data: